name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 56.228.22.29
          username: ubuntu
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACCyi7nmZrf5tGaB4SMZTAxuoRT4xxGy8G/an/KnROK9jAAAAJi0cSmStHEp
            kgAAAAtzc2gtZWQyNTUxOQAAACCyi7nmZrf5tGaB4SMZTAxuoRT4xxGy8G/an/KnROK9jA
            AAAEDqKBAqVFQ05gAuGqSQH1UZc1uFolemWY5ejts7voh6EbKLueZmt/m0ZoHhIxlMDG6h
            FPjHEbLwb9qf8qdE4r2MAAAAEmdpdGh1Yi1hY3Rpb25zLWVjMgECAw==
            -----END OPENSSH PRIVATE KEY-----
          script: |
            cd /home/ubuntu
            git pull origin main
            npm install
            pm2 restart app || pm2 start server.js --name app