jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print debug info
        run: |
          echo "HOST: ${{ secrets.EC2_HOST }}"
          echo "USER: ${{ secrets.EC2_USER }}"
          echo "KEY START:"
          echo "${{ secrets.EC2_SSH_KEY }}" | head -n 3
          echo "KEY END"

      - name: SSH & deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/myapp
            git pull origin main
            npm install
            pm2 start server.js --name app